import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBarMain from "@/components/navBarMain";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBarMain />
        <h1 className="text-center font-bold text-blue-600">Southeast Asia University</h1>
        <hr className="my-10 w-3/4 m-auto"/>

        {children}

        <hr className="my-10 w-3/4 m-auto" />

        <Footer />

      </body>
    </html>
  );
}

